Creating cluster assignments and calculating for dataset for IL2
meyer-lab/tensor-gmm pull request #114
Opened 2022-09-07 03:40 UTC by andrewram4287

2022-09-07 13:40 UTC, aarmey requested changes

2022-09-07 13:40 UTC, aarmey commented on gmm/imports.py
> +    return flowXA, celltypeXA, flowDF
This almost certainly breaks other code. Have you checked that this builds and passes tests?

2022-09-07 13:40 UTC, aarmey commented on gmm/imports.py
> +from types import CellType
Doesn't look like you use this import?

2022-09-07 13:40 UTC, aarmey commented on gmm/figures/figure4.py
> +    for i in range(0, resps.shape[1]):
Can you comment on what this is doing? There should be a way to go about it without all the loops...

2022-09-07 18:38 UTC, andrewram4287 commented on gmm/figures/figure4.py
> +    for i in range(0, resps.shape[1]):
Sounds good working on it!

2022-09-07 19:22 UTC, andrewram4287 commented on gmm/figures/figure4.py
> +    for i in range(0, resps.shape[1]):
@aarmey How do i ensure that a cluster is assigned to a specific cell type based on the responsibilities? Is the only way to do this via adj_rand_score?

2022-09-07 23:15 UTC, aarmey commented on gmm/figures/figure4.py
> +    for i in range(0, resps.shape[1]):
I think you should first just make a [confusion matrix](https://en.wikipedia.org/wiki/Confusion_matrix) between manually gating and the clusters.

2022-09-09 17:36 UTC, andrewram4287 commented on gmm/figures/figure4.py
> +    for i in range(0, resps.shape[1]):
@aarmey I am still having trouble how we can compare cluster assignments from the responsibilities to the actual true cell type label. I understand it logically but I dont understand how to implement the process

2022-09-11 00:14 UTC, aarmey commented on gmm/figures/figure4.py
> +    for i in range(0, resps.shape[1]):
@borcuttjahns I think you had this figured out?

2022-09-11 21:18 UTC, andrewram4287 commented on gmm/figures/figure4.py
> +    for i in range(0, resps.shape[1]):
I am implemented Brians implementation before don't know a better way of going about the process without all the for loops

2022-09-11 21:21 UTC, aarmey commented on gmm/figures/figure4.py
> +    for i in range(0, resps.shape[1]):
Oh, apologies, I could have been clearer. I meant that I would look into something without the for loops.

2022-09-12 16:49 UTC, andrewram4287 commented on gmm/figures/figure4.py
> +def cluster_type(drugXA, fac, typeXA, ax):
@aarmey Is this method better than the previous for comparing the predicted and actual cell assignments

2022-09-12 16:55 UTC, aarmey commented on gmm/figures/figure4.py
> +def cluster_type(drugXA, fac, typeXA, ax):
Yes!! You can use the `axis` argument of `argmax()` to get rid of the loops.

2022-09-12 21:54 UTC, andrewram4287 commented
@aarmey I also added a bit more of an efficient soft clustering methods as well, other than that the PR should be ready to merge!

2022-09-12 22:09 UTC, aarmey approved these changes
Check that this builds. Otherwise, this looks ready to merge to me!

2022-09-13 16:24 UTC, merged