Separate Factors and Allow Negs
meyer-lab/tensor-gmm pull request #118
Opened 2022-09-13 23:39 UTC by borcuttjahns

@aarmey @andrewram4287 Sharing this now as a bookmark slash opportunity for you to play with the revised method. It works and nails the synthetic scene and IL-2 datasets but still seems to fail for the PopAlign stuff which I'll investigate. Let me know your thoughts and feel free to make any efficiency or clarity-related edits - just shoot me a message if you plan to!

2022-09-14 02:50 UTC, aarmey commented
Excellent! Just a note that running Fig. 4 with anything other than rank 3 leads to an error. I think this may be an issue with `cluster_type()`, though, and not the changes in this PR.

2022-09-14 14:47 UTC, andrewram4287 commented
@aarmey I am currently running Fig4 with other ranks and I am not receiving an error on my end....

2022-09-14 16:29 UTC, aarmey commented
Ok. Maybe I messed something up.

2022-09-14 22:14 UTC, borcuttjahns commented
@aarmey @andrewram4287 Ok so I think this is currently working but there are still a couple of issues that should be talked about.

1) Because in cases where NK values vary by condition, I still have to make that condition factor positive by using an exponential. This sort of defeats the purpose of this development for that particular factor but negatives are still handled.
2) The method seems to work but despite the heightened freedom from separating means and covariances it seems to fit the PopAlign data with worse likelihood. It also (from mean factors) doesn't identify the "correct" divergent drugs although I haven't checked if it does from covariance factors.

I think I'm going to leave this here at least for the time being until we can meet to discuss - if either of you want to test it or improve it feel free!

2022-09-14 22:22 UTC, aarmey commented
Regarding 1: I think our same reasoning applies and we should fully separate the nk factors from the rest.

Regarding 2: Now that we don't require positive values, it's likely better to use PCA instead of NMF for the RNAseq initial reduction. A nice additional benefit is it'll be way faster.

2022-09-14 22:27 UTC, aarmey commented
Finally, I'm happy merging this if it looks like the flow analysis is improved. We don't really know what to expect with the RNAseq data, so I don't make much of surprising results there.

2022-10-30 00:10 UTC, aarmey requested changes
Some questions.

2022-10-30 00:10 UTC, aarmey commented on gmm/tests/test_GMM.py
> +@pytest.mark.parametrize("nk_r", [True, False])
Can you move these down to their old position, so I can see the diff? Or, is there a reason these should be moved up?

2022-10-30 00:10 UTC, aarmey commented on gmm/figures/figure7.py
> -    drug_gene_plot(facXA, "Budesonide", nfac, ax[5], max=True)
What was this and why did it get removed?

2022-10-30 00:10 UTC, aarmey commented on gmm/figures/figure4.py
> +
Lint.

2022-10-30 00:10 UTC, aarmey commented on gmm/tensor.py
> +import jax.lax as jlx
Are you using any of these new imports? They seem like very strange items...

2022-10-31 01:46 UTC, andrewram4287 commented on gmm/figures/figure7.py
> -    drug_gene_plot(facXA, "Budesonide", nfac, ax[5], max=True)
No, I think it was on accident.

2022-10-31 01:47 UTC, andrewram4287 commented on gmm/tensor.py
> +import jax.lax as jlx
I removed a couple of imports!

2022-10-31 01:50 UTC, andrewram4287 commented on gmm/tests/test_GMM.py
> +@pytest.mark.parametrize("nk_r", [True, False])
I think @borcuttjahns moved them, but I can put them back to their original position if you'd like.

2022-10-31 14:50 UTC, aarmey requested changes
More suggestions.

2022-10-31 14:50 UTC, aarmey commented on gmm/tensor.py
> +from jax.experimental.host_callback import id_print
I don't see `id_print` being used.

2022-10-31 14:50 UTC, aarmey commented on gmm/tensor.py
> +        nN = np.delete(nN, 2)
I don't follow what's going on here. Why are you deleting the third element? Can you provide a comment for what this block does?

2022-10-31 14:50 UTC, aarmey commented on gmm/tensor.py
> +        covarFacS.pop(1)
Why are you poping an element here?

2022-10-31 14:50 UTC, aarmey commented on gmm/tensor.py
> +        covar = np.einsum(
This should almost certainly be `jnp`

2022-10-31 14:50 UTC, aarmey commented on gmm/tensor.py
> +        # cp_factors = self.reorient_factors(cp_factors)
Remove unused code.

2022-10-31 14:50 UTC, aarmey commented on gmm/tensor.py
> +    def reorient_factors(self, X):
This does not use anything from the class (no `self.X`). Should not be defined within the class.

2022-10-31 14:50 UTC, aarmey commented on gmm/tensor.py
> +    def reorient_factors(self, X):
Also, [`cp_flip_sign`](https://github.com/tensorly/tensorly/blob/main/tensorly/cp_tensor.py#L329) does this for you.

2022-10-31 16:39 UTC, andrewram4287 commented on gmm/tensor.py
> +        covarFacS.pop(1)
This is to get rid of the "signal" dimension. The covariance factor of (Signal x Signal x Rank) is rearranged in a different part of the code

2022-10-31 16:43 UTC, andrewram4287 commented on gmm/tensor.py
> +        nN = np.delete(nN, 2)
Again, this is to ensure that we are not solving for the covariance of the signals.

2022-11-01 19:56 UTC, aarmey commented
This looks close enough—merging!

2022-11-01 19:56 UTC, merged