New CoH dataset
meyer-lab/tensor-gmm pull request #120
Opened 2022-09-30 15:12 UTC by andrewram4287

Updating the CoH will new patients. Only using patients that have experiments from Untreated, 50mg IL6, IL10, IL2, IFNg, and IL4. Implemented regression model based on the factors. Created functions to plot factors, covariances, and raw data as well.

2022-10-30 00:04 UTC, aarmey requested changes
I need an idea of what the intended changes are here.

2022-10-31 01:42 UTC, andrewram4287 commented
> I need an idea of what the intended changes are here.

Wrote a description, let me know if further clarification is needed.

2022-10-31 01:59 UTC, aarmey commented
Ok, there are a ton of changes here. Is there any way to split it up?

2022-10-31 02:45 UTC, andrewram4287 commented
> Ok, there are a ton of changes here. Is there any way to split it up?

Yeah i can do that if it'll make it easier to interpret. I can make more PR and separate out the changes if thats the easiest way to go about it

2022-11-01 19:57 UTC, aarmey commented
@andrewram4287 please resolve conflicts here to start on this PR, then check that it builds.

2022-11-02 18:21 UTC, aarmey requested changes
A few comments. Why are there so many changes to figures that don't involve the CoH data? Also, it would be helpful to add a unit test for the import functions.

2022-11-02 18:21 UTC, aarmey commented on gmm/tests/test_GMM.py
> +def test_cov_fit():
These are duplicated now due to failed merge.

2022-11-02 18:21 UTC, aarmey commented on gmm/tensor.py
> +    def reorient_factors(self, numb_fact):
Is this relevant to the PR?

2022-11-02 18:21 UTC, aarmey commented on gmm/tensor.py
> +import jax.lax as jlx
Unused.

2022-11-02 18:21 UTC, aarmey commented on gmm/tensor.py
> +from re import S
Unused.

2022-11-03 02:24 UTC, closed without merging