Normalzing covariance factors and creating functions for factor plots
meyer-lab/tensor-gmm pull request #124
Opened 2022-11-03 22:31 UTC by andrewram4287

Creating functions to plot covariance and mean factors. Incorporated normalization for covariance factors

2022-11-04 02:33 UTC, aarmey requested changes
A few questions.

2022-11-04 02:33 UTC, aarmey commented on gmm/tensor.py
> +            self.covFacs[i] = self.covFacs[i]/np.linalg.norm(self.covFacs[i],axis=0)
It looks like this removes the scaling, but would it be good to keep this around somewhere? (In the CP tensor class, these are stored as `weights`.)

2022-11-04 02:33 UTC, aarmey commented on gmm/tensor.py
> +        covarSignal = covarSignal/np.linalg.norm(covarSignal, axis=(0,1))
Same question about `weights` here.

2022-11-04 02:33 UTC, aarmey commented on gmm/tensor.py
> +    def norm_covariances(self):
When is this run? If this doesn't materially affect the results, should we perhaps run this at the end of fitting?

It would be good to come up with a test to check that this does not affect anything...

2022-11-04 14:13 UTC, andrewram4287 commented on gmm/figures/figure6.py
> +    covarDim, covarSig = fac.norm_covariances()
@aarmey This where I am normalizing the covariances, but I think you are right that maybe having it be the last step in the analysis would make more sense

2022-11-04 14:14 UTC, aarmey commented on gmm/figures/figure6.py
> +    covarDim, covarSig = fac.norm_covariances()
Yeah—you can keep your function as-is, but just run it at the end of the fitting.

2022-11-05 03:10 UTC, aarmey requested changes

2022-11-05 03:10 UTC, aarmey commented on gmm/tests/test_GMM.py
> +    TestCase.assertNotEqual(fac.covFacs[0],fac.covarianceFactors[0], "Error")
I'm confused. You want to test whether they are unchanged, but your assertion here is that they are not equal? Wouldn't they be equal if unchanged? Also, the built covariances should be unchanged, but the factors should be changed.

Also, this is the wrong function for arrays. Use numpy's assert_allclose: https://numpy.org/doc/stable/reference/generated/numpy.testing.assert_allclose.html#numpy.testing.assert_allclose

2022-11-05 03:10 UTC, aarmey commented on gmm/tests/test_GMM.py
> +    assert np.testing.assert_allclose(fac.covFacs[0],newCovFacs[0],rtol=0.01)
Some of the above applies here, too.

2022-11-06 03:22 UTC, andrewram4287 commented
@aarmey both tests aren't working, but I believe my implementation to rebuild the tensors and redo the normalization is correct.

2022-11-06 18:21 UTC, aarmey commented
@andrewram4287 I've fixed the tests here. I think all that needs updating are the figures. Note that I've applied the weights to just one of the factors, so there is no separate weights storage anymore.

2022-11-07 15:21 UTC, andrewram4287 commented
@aarmey  `test_cov_fit` is not passing the current test because the weights are put into the `covars` Also, when we build the covariance 3-d tensor for the signals, do we rebuild the covariance the same way as before, using `covars @ covars.T`, or just `covars`?

2022-11-07 15:26 UTC, aarmey commented
@andrewram4287 `test_cov_fit` also fails occasionally on master, too. Let's just remove it. (Not a great test.)

Reconstructing the covariance matrices is exactly the same as before.

2022-11-07 15:33 UTC, andrewram4287 commented
> @andrewram4287 `test_cov_fit` also fails occasionally on master, too. Let's just remove it. (Not a great test.)
> 
> Reconstructing the covariance matrices is exactly the same as before.

@aarmey do we want the covariance signals (`covars`) to be normalized as well?

2022-11-07 15:52 UTC, aarmey commented
You tell me—would it be better to have the scaling stored as separate weights, or in `covars`?

2022-11-07 16:15 UTC, andrewram4287 commented
> You tell me—would it be better to have the scaling stored as separate weights, or in `covars`?

I feel like it would be better to keep in separate weights, since we want to compare `covars` for different rankings, and it would easier to interpret with the weights stored separately

2022-11-07 16:44 UTC, aarmey requested changes
Weights are now separate. One comment.

2022-11-07 16:44 UTC, aarmey commented on gmm/figures/figure6.py
> +        dff = pd.DataFrame(
Why doesn't this use `get_covariances_xarray()`?

2022-11-07 16:47 UTC, andrewram4287 commented on gmm/figures/figure6.py
> +        dff = pd.DataFrame(
@aarmey `get_covariances_xarray()` rebuilds the tensor based on all the covariance factors. Instead we want to plot the covariance factors

2022-11-07 16:49 UTC, aarmey commented on gmm/figures/figure6.py
> +        dff = pd.DataFrame(
Oh I see. Ok, we can keep this, but should probably make a `get_covariance_factors()` at some point.

If this builds we can merge?

2022-11-07 16:52 UTC, andrewram4287 commented on gmm/figures/figure6.py
> +        dff = pd.DataFrame(
@aarmey I will do that next. Yes looks like we can merge!

2022-11-07 17:23 UTC, merged