Data xarray
meyer-lab/tensor-gmm pull request #41
Opened 2022-04-12 21:42 UTC by andrewram4287

2022-04-13 19:08 UTC, aarmey commented
@andrewram4287 can you remove the least squares fitting from this branch, then tag me? It's helpful to keep the changes here as minimal as possible.

2022-04-13 19:09 UTC, aarmey commented on gmm/imports.py
> +def smallDF(fracCells,xArray = False):
I'd set this up to _only_ use xarray. Once we have it setup, there's no reason to do it any other way.

2022-04-14 03:46 UTC, andrewram4287 commented
@aarmey I was able to make the smallDF and probGMM only use the Xarray!!

2022-04-14 05:04 UTC, aarmey commented on gmm/GMM.py
> +    zflowDF = zflowDF.drop_sel({"Marker": "pSTAT5"})
Started on making this work.

2022-04-14 05:05 UTC, aarmey commented on gmm/GMM.py
> +def cvGMM(zflowDF: xa.DataArray, maxcluster: int):
This needs the Cell Types column. Perhaps this can be provided as a separate variable?

2022-04-14 05:05 UTC, aarmey commented on gmm/GMM.py
> +    log_resp = np.reshape(log_resp, (zflowDF.shape[0], zflowDF.shape[1], zflowDF.shape[2], zflowDF.shape[3], -1))
I didn't do this correctly, but you should be able to do a reshape here to avoid complicated indexing later. Can you take a look?

2022-04-14 05:06 UTC, aarmey commented on gmm/GMM.py
> +                                                       np.exp(log_resp[i, j, k, :]), 1e-6, "full")
Here's where the indexing is simplified, but this might need to be adjusted.

2022-04-14 05:11 UTC, aarmey commented
@andrewram4287 excellent! I made some small simplifications here and took some notes. It's just a matter of fixing the kinks to get this to build now. Take a look and let me know if you get stuck.

2022-04-14 18:27 UTC, andrewram4287 commented
@aarmey everything but the minimization function is included and works with Xarrays!

2022-04-15 12:54 UTC, aarmey requested changes
Still see a few things broken.

2022-04-15 12:54 UTC, aarmey commented on gmm/tensor.py
> -markerslist = ["Foxp3", "CD25", "CD4", "CD45RA", "pSTAT5"]
Why do these have to be flipped?

2022-04-15 12:54 UTC, aarmey commented on gmm/tensor.py
> +# def comparingGMM(zflowDF: xa.DataArray, tMeans: xa.DataArray, tCovar: xa.DataArray, nk: np.ndarray):
Can you get this working rather than commenting it out?

2022-04-15 12:54 UTC, aarmey commented on gmm/figures/figure4.py
> +    # _ = comparingGMM(zflowTensor, tMeans, tCovar, nkCommon)
It should still be possible to run this.

2022-04-15 12:54 UTC, aarmey commented on gmm/GMM.py
> +    nk = xa.DataArray(np.full((n_clusters, len(times), len(doses), len(ligand)), np.nan), coords={
Why did these have to change?

2022-04-15 12:54 UTC, aarmey commented on gmm/GMM.py
> +    grid_search.fit(X, true_types.values.flatten())
I don't think this data is matched up correctly. Look at Fig. 1 in the build.

2022-04-15 12:54 UTC, aarmey commented on gmm/GMM.py
> +    X = np.reshape(zflowDF.to_numpy(), (-1, zflowDF.shape[0]))  # Creating matrix that will be used in GMM model
It's possible this reshape isn't in the order we expect.

2022-04-15 12:54 UTC, aarmey commented on gmm/GMM.py
> +    grid_search.fit(X, true_types.values.flatten())
Actually, this is almost certainly the problem. When we organize zflowDF into an xarray, it organizes the various conditions. Before that, I'm guessing the flow experiments are not in a particular order. We probably need to keep true_types as an xarray as well, and then flatten it in the same way as we do with zflowDF.

2022-04-15 12:54 UTC, aarmey commented on gmm/GMM.py
> +    nk = xa.DataArray(np.full((n_clusters, len(times), len(doses), len(ligand)), np.nan), coords={
Why do you have to change the order from ligand, dose, time; to time, dose, ligand?

2022-04-15 14:34 UTC, andrewram4287 commented on gmm/tensor.py
> -markerslist = ["Foxp3", "CD25", "CD4", "CD45RA", "pSTAT5"]
I wanted to be consistent with the order for the markers throughout each function. Previously, the order was different in the import.py

2022-04-15 14:34 UTC, andrewram4287 commented on gmm/tensor.py
> +# def comparingGMM(zflowDF: xa.DataArray, tMeans: xa.DataArray, tCovar: xa.DataArray, nk: np.ndarray):
Yes I can!

2022-04-15 14:35 UTC, andrewram4287 commented on gmm/GMM.py
> +    nk = xa.DataArray(np.full((n_clusters, len(times), len(doses), len(ligand)), np.nan), coords={
Once again, I wanted to stay consistent throughout our code. In the imports.py, the order is time, dose, and ligand so I needed to change the rest of the code to match the indices for tensors with that order

2022-04-15 14:37 UTC, andrewram4287 commented on gmm/GMM.py
> +    grid_search.fit(X, true_types.values.flatten())
That's what I was thinking as well. I will get on that!

2022-04-15 14:39 UTC, andrewram4287 commented on gmm/GMM.py
> +    X = np.reshape(zflowDF.to_numpy(), (-1, zflowDF.shape[0]))  # Creating matrix that will be used in GMM model
I also had worries about that, before I created a for loop to keep track of everything in order since I don't exactly know if "np.reshape" is doing that for us. What would be the best way to proceed with this issue @aarmey?

2022-04-15 17:20 UTC, aarmey commented on gmm/tensor.py
> -markerslist = ["Foxp3", "CD25", "CD4", "CD45RA", "pSTAT5"]
Ok, that's reasonable.

2022-04-15 17:21 UTC, aarmey commented on gmm/GMM.py
> +    nk = xa.DataArray(np.full((n_clusters, len(times), len(doses), len(ligand)), np.nan), coords={
Ok, sounds good.

2022-04-15 17:22 UTC, aarmey commented on gmm/GMM.py
> +    X = np.reshape(zflowDF.to_numpy(), (-1, zflowDF.shape[0]))  # Creating matrix that will be used in GMM model
Try changing `cell_types` first. That's most likely the root of the problem. There are ways to adjust how reshape is done, but if everything is handled in the same way then there shouldn't be a need to worry about it.

2022-04-15 21:37 UTC, andrewram4287 commented on gmm/GMM.py
> +    X = np.reshape(zflowDF.to_numpy(), (-1, zflowDF.shape[0]))  # Creating matrix that will be used in GMM model
I tried making an` Xarray` with the same size as the zflowDF, but this one included the cell types. Instead of the usual markers, the column included for `Marker` was `["Foxp3", "CD25", "CD45RA","Cell Type"]`. I then reshaped the matrix `CellTypeXarray `to be the same as the `zflowDF` that would be inserted into the GMM, hoping that I could just call the last column to give the "Cell Type" and plug into the `GMM.fit`. But we hoping that each row represents one cell and that each column represented a different marker. But I don't think that's the case for `np.reshape` because I received the following result 
![Screen Shot 2022-04-15 at 2 30 02 PM](https://user-images.githubusercontent.com/91349614/163635056-e2e8aa1e-54cc-4d0e-aea4-4af48515bfb5.png)

2022-04-15 22:07 UTC, aarmey commented on gmm/GMM.py
> +    X = np.reshape(zflowDF.to_numpy(), (-1, zflowDF.shape[0]))  # Creating matrix that will be used in GMM model
Try converting the data to a numpy array, then you can use [np.swapaxes](https://numpy.org/doc/stable/reference/generated/numpy.swapaxes.html#numpy.swapaxes) before np.reshape to control the ordering.

2022-04-20 03:38 UTC, andrewram4287 commented
I think I got it to work by using Xa.unstack!

2022-04-20 13:23 UTC, merged