CreatingNewVectorCpFunctions
meyer-lab/tensor-gmm pull request #43
Opened 2022-04-21 04:39 UTC by andrewram4287

2022-04-21 04:41 UTC, andrewram4287 commented
Currently the Cp factors are not the same, would you be able to check where I am going wrong either from Cp to vector or from vector to Cp?

2022-04-21 15:02 UTC, aarmey requested changes

2022-04-21 15:02 UTC, aarmey commented on gmm/figures/figure4.py
> +    vectorFac = vector_to_cp(cpVector, rank, tMeans)
This test should go into `test_GMM.py`.

2022-04-22 03:12 UTC, andrewram4287 commented on gmm/tensor.py
> +    tensor = tl.cp_to_tensor(facinfo)
That makes more sense! I misinterpreted your message before.

2022-04-22 13:55 UTC, aarmey approved these changes
Excellent. Merging!

You should now be able to fit the factors, instead of tMeans in full tensor form. Do you see how?

2022-04-22 13:55 UTC, merged