Cross Validation of Tensor-GMM
meyer-lab/tensor-gmm pull request #62
Opened 2022-05-20 16:29 UTC by borcuttjahns

A little clunky but uniquely shuffles and performs K fold Cross Val for every experiment/condition.

2022-05-20 16:40 UTC, aarmey requested changes

2022-05-20 16:40 UTC, aarmey commented on gmm/tensor.py
> +        for timeCoord in np.arange(0, cellTensor.Time.size):
Not following what you're doing here. Wouldn't splits just be over the cell axis?

2022-05-20 16:54 UTC, borcuttjahns commented on gmm/tensor.py
> +        for timeCoord in np.arange(0, cellTensor.Time.size):
So here I'm defining holders for the test and training data. These have dimensions of (5 markers x Cells in a fold x Time x Dose x Ligand) etc. - so together they have the same dimensions as the original data tensor. I later fill them in with shuffled cellular data.

2022-05-20 16:58 UTC, aarmey commented on gmm/tensor.py
> +        for timeCoord in np.arange(0, cellTensor.Time.size):
But why do you ever have to fold or unfold?

2022-05-20 17:01 UTC, borcuttjahns commented on gmm/tensor.py
> +        for timeCoord in np.arange(0, cellTensor.Time.size):
I'm sorry but I'm a bit confused as to what you mean here. Do you mean I should have just split the data into K parts and not worried about shuffling?

I think I may have gone a bit overkill but I shuffle every experiment uniquely rather than use the same indices/folds for every one - does that answer your question?

2022-05-20 22:51 UTC, borcuttjahns commented
Third time's the charm? Should be simplified and correct now

2022-05-21 02:51 UTC, aarmey approved these changes
Simplified this a bit more. Going to merge now since the build will take a while.

2022-05-21 02:51 UTC, merged