Sc analysis
meyer-lab/tensor-gmm pull request #74
Opened 2022-06-17 17:45 UTC by andrewram4287

2022-06-17 21:42 UTC, aarmey requested changes
What does this do? What does it aim to do? Please describe.

2022-06-20 20:16 UTC, andrewram4287 commented
> What does this do? What does it aim to do? Please describe.

Uploaded all the PopAlign data, filtered genes, performed NNMF, converted from DF to Xarray, ran minimization of loglik for the given data to determine the factors, and also ran cross validation to find the best factor/cluster combination 

Also, added more descrioption to each function

2022-06-20 20:51 UTC, aarmey requested changes
A couple small adjustments.

2022-06-20 20:51 UTC, aarmey commented on gmm/figures/figure7.py
> +def geneGMM_CV(X, numFolds: int, numClusters: int, numRank: int, maxiter=300):
Is there a reason you're not able to use the existing `tensorGMM_CV()`?

2022-06-20 20:51 UTC, aarmey commented on gmm/figures/figure7.py
> +#     jax.config.update('jax_platform_name', 'cpu')
You can just leave this one line commented out at the top of the file. No need for a whole function.

2022-06-20 20:57 UTC, andrewram4287 commented on gmm/figures/figure7.py
> +def geneGMM_CV(X, numFolds: int, numClusters: int, numRank: int, maxiter=300):
Nope! Just fixed it!

2022-06-20 21:02 UTC, aarmey commented on gmm/figures/figure7.py
> +    genesN = normalizeGenes(genesDF, geneNames)
@andrewram4287 last question—you don't seem to ever use `genesN` here. Is that intended?

2022-06-20 21:03 UTC, aarmey approved these changes

2022-06-20 21:10 UTC, andrewram4287 commented on gmm/figures/figure7.py
> +    genesN = normalizeGenes(genesDF, geneNames)
Shoot that is not intended. `mu_sigma(genesDF,geneNames) ` should be `mu_sigma(genesN,geneNames) `. I will run that again and get the correct csv data uploaded with the normalization included.

2022-06-21 17:51 UTC, merged