Two ways to calculate NK
meyer-lab/tensor-gmm pull request #82
Opened 2022-06-23 23:00 UTC by andrewram4287

2022-07-01 03:03 UTC, aarmey commented
@andrewram4287 can you write a test that calls this function with inputs of the right shapes? You can fill them with dummy numbers—like a matrix of ones. This will be helpful for ensuring it is setup correctly.

2022-07-01 19:09 UTC, aarmey requested changes

2022-07-01 19:09 UTC, aarmey commented on gmm/tests/test_GMM.py
> +def test_loglikelihood():
This function should directly call `comparingGMMjax_NK()` so you are only testing that code. Like I mentioned, you can make dummy arguments from scratch. The current code cannot be correct, because `nk` should be differently sized depending on whether it is a factor matrix or vector describing the constant values.

2022-07-01 19:09 UTC, aarmey commented on gmm/tensor.py
> +    assert nk.ndim == 1
Isn't `nk` now supposed to be a factor matrix? In that case, it cannot be a vector.

2022-07-01 19:10 UTC, aarmey commented on gmm/tensor.py
> +    nkl = jnp.log(nk / jnp.sum(nk))
I had noted about this needing to have an `axis` argument, because `nk` is now a matrix.

2022-07-01 19:11 UTC, aarmey commented on gmm/tensor.py
> +        [
Did this change or is this just linting?

2022-07-01 20:20 UTC, andrewram4287 commented on gmm/tensor.py
> +        [
Just linting I believe

2022-07-01 20:20 UTC, andrewram4287 commented on gmm/tensor.py
> +    assert nk.ndim == 1
Ok I will change that!

2022-07-01 22:14 UTC, andrewram4287 commented on gmm/tests/test_GMM.py
> +def test_loglikelihood():
Ok I think i was able to alter it correctly based on the tMeans tensor.

2022-07-02 14:28 UTC, aarmey requested changes

2022-07-02 14:28 UTC, aarmey commented on gmm/tensor.py
> +    mp = jnp.einsum("iz,jz,kz,ijok->iok", *meanFact, tPrecision)
`meanFact` still has five dimensions, so this reduced `einsum` is failing.

2022-07-02 14:28 UTC, aarmey commented on gmm/tests/test_GMM.py
> +    _, meanFact,covFac = vector_to_cp_pt(x0, rank=3, shape=PAShape)
You should build `meanFact` and `precBuild` manually, like I suggested. `vector_to_cp_pt` does not provide the right shapes.

2022-07-02 23:10 UTC, andrewram4287 commented on gmm/tensor.py
> +    mp = jnp.einsum("iz,jz,kz,ijok->iok", *meanFact, tPrecision)
I was able to change the shape of meanFact and tPrecision! But now the einsum seems to be failing

2022-07-04 03:48 UTC, aarmey approved these changes
I think this was an issue with the test. I have a fix here that is passing. Please look everything over and, if it all makes sense, you can merge.

2022-07-04 22:09 UTC, merged