Creating R2X for DF from NMF
meyer-lab/tensor-gmm pull request #83
Opened 2022-06-24 16:20 UTC by andrewram4287

2022-07-06 06:25 UTC, aarmey requested changes
Check the git action test. There's a testing error.

2022-07-06 06:25 UTC, aarmey commented on gmm/figures/figure5.py
> +    #     row["Rank"] = ["Rank:" + str(ranknumb[i])]
Do you mean for this to be commented out?

2022-07-06 06:25 UTC, aarmey commented on gmm/scImport.py
> +    drugScreen = drugScreen.astype(np.int32)
Why an int?

2022-07-06 06:25 UTC, aarmey commented on gmm/scImport.py
> +import tensorly as tl
I don't see tensorly used here?

2022-07-06 06:25 UTC, aarmey commented on gmm/scImport.py
> +from inspect import getinnerframes
Are these imports used?

2022-07-06 06:25 UTC, aarmey commented on gmm/scImport.py
> +    _, geneFactors, _ = geneNNMF(finalDF, k=rank, verbose=0, maxiteration=maxit)
Since geneNNMF is already returning the SSE here, why not just always calculate R2X?

2022-07-06 06:25 UTC, aarmey commented on gmm/scImport.py
> +    _, geneFactors, _ = geneNNMF(finalDF, k=rank, verbose=0, maxiteration=maxit)
Also, R2X is really only relevant for centered data, not NNMF. It's better to just report/plot SSE rather than R2X.

2022-07-06 06:25 UTC, aarmey commented on gmm/scImport.py
> +def tensor_R2X(tensor, maxrank, maxit):
Think you can delete this given the comment above.

2022-07-12 00:30 UTC, andrewram4287 commented
> 

This test should be fixed now!

2022-07-12 14:51 UTC, aarmey approved these changes
Great. This all looks good to me. Let's just wait to see if it builds before merging.

2022-07-12 22:06 UTC, aarmey commented
Great. Merging!

2022-07-12 22:06 UTC, merged