Allowing NK to vary
meyer-lab/tensor-gmm pull request #88
Opened 2022-07-18 23:33 UTC by andrewram4287

Altering the minimization function to allow the variability of NK to vary over cluster and rank. Needed to alter a few functions in order to rebuild and guess for NK values correctly. Altered shape of data to be 3 instead of 5 to alllow for the function of `comparingGMMjax_NK` and `axloglik_ptnnp_NK` to work

2022-07-19 03:04 UTC, aarmey requested changes
A few readability suggestions.

2022-07-19 03:04 UTC, aarmey commented on gmm/tensor.py
> +        optNK, optCP, optPT = vector_to_cp_pt(opt.x, rank, meanShape)
If the only difference in the two branches of the if statement is nk_rearrange, you can just make this one line: `optNK, optCP, optPT = vector_to_cp_pt(opt.x, rank, meanShape, nk_rearrange= nk_rearrange)`

2022-07-19 03:04 UTC, aarmey commented on gmm/figures/figure7.py
> +    # coords = {"Cluster": clustArray, "Factor": cmpCol, "Drug": drugXA.coords["Drug"]}
Why comment all this out?

2022-07-19 03:04 UTC, aarmey commented on gmm/figures/figure10.py
> +This creates Figure 10.
Can we put the purpose of each figure into the docstring? I can get the figure number from the filename.

2022-07-19 04:26 UTC, andrewram4287 commented on gmm/figures/figure7.py
> +    # coords = {"Cluster": clustArray, "Factor": cmpCol, "Drug": drugXA.coords["Drug"]}
Forgot to change it back, on it!

2022-07-20 03:15 UTC, aarmey approved these changes
Looks good to merge!

2022-07-20 14:17 UTC, merged